language: cpp
compiler: gcc

before_install:
  # We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  #- sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools

install:
  # We want to compile with g++ 4.8 when rather than the default g++
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

script: qmake -r && make
